### ISSUE TITLE
Change the name of the target file

### ISSUE THREAD

**Issue by andreasciamanna** [scruffyfox/bitrise-amazon-s3-uploader#5]
As far I can see, I can only specify the file that I want to upload:

```yaml
inputs:
  - aws_access_key: "$AWS_ACCESS_KEY"
  - aws_secret_key: "$AWS_SECRET_ACCESS_KEY"
  - bucket_name: "$AWS_S3_DEPLOY_BUCKET"
  - path_in_bucket: "latest"
  - file_path: "$BITRISE_IPA_PATH"
```

My use case is that some testers need to always use the latest build, so they can rely on always using the same URL for downloading the file.
